### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by frekw** [opencensus-beam/oc_google_reporter#4]
Hey!

Some dependencies, like `hackney` and `opencensus` are out of date. Would be nice if they could be updated or the versions relaxed to avoid warnings when building this project.

**Comment by tsloughter** [comment]
Are you using them with rebar3 or mix? We can definitely relax the versions, the reason I often forget to is that rebar3 doesn't care about versions, hehe, so this really only effects mix.

**Comment by tsloughter** [comment]
pls send a PR with what you think are good relaxed versions and I can merge it and cut a new release.

**Comment by frekw** [comment]
Heh, I'm using them with mix. I'll send a PR!

**Comment by frekw** [comment]
Just realized I have no idea how `rebar.lock` interacts with Mix. I'll do some Googling!

**Comment by tsloughter** [comment]
It doesn't. Your adding version constraints like `~> 0.4` or whatever to rebar.config will update the lock file but the version constraint itself will be used in the hex package when published and mix (and rebar3) will use the hex metadata.

**Comment by frekw** [comment]
Ok, see #5. I hope I got it right!
